name: tesseract_web_example
publish_to: none
description: Demonstrates how to use the tesseract_web plugin.
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.0.1
  cupertino_icons: ^1.0.2
  tesseract_web:
    path: ../

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

get_cli:
  sub_folder: false

flutter:
  uses-material-design: true
  assets:
    - assets/
